webapp/news/models.py
from datetime import datetime
from sqlalchemy.orm import relationship
from webapp.db import db


class News(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String, nullable=False)
    url = db.Column(db.String, unique=True, nullable=False)
    published = db.Column(db.DateTime, nullable=False)
    text = db.Column(db.Text, nullable=True)

    def comments_count(self):
        return Comments.query.filter(Comments.news_id == self.id).count()

    def __repr__(self):
        return "<News {} {}>".format(self.title, self.url)


class Comments(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    text = db.Column(db.Text, nullable=False)
    created = db.Column(db.DateTime, nullable=False, default=datetime.now())
    news_id = db.Column(
        db.Integer,
        db.ForeignKey("news.id", ondelete="CASCADE"),
        index=True
    )
    user_id = db.Column(
        db.Integer,
        db.ForeignKey("user.id", ondelete="CASCADE"),
        index=True
    )
    news = relationship("News", backref="comments")
    user = relationship("User", backref="comments")

    def __repr__(self):
        return "<Comment {}>".format(self.id)

webapp/news/forms.py
from flask_wtf import FlaskForm
from wtforms import HiddenField, StringField, SubmitField
from wtforms.validators import DataRequired, ValidationError

from webapp.news.models import News


class CommentForm(FlaskForm):
    news_id = HiddenField("ID новости", validators=[DataRequired()])
    comment_text = StringField("Ваш комментарий", validators=[DataRequired()], render_kw={"class": "form-control"})
    submit = SubmitField("Отправить!", render_kw={"class": "btn btn-primary"})

    def validate_news_id(self, news_id):
        if not News.query.get(news_id.data):
            raise ValidationError("Новости с таким id не существует.")

webapp/news/views.py
from flask import abort, Blueprint, current_app, flash, render_template, redirect, request
from flask_login import current_user, login_required

from webapp.db import db
from webapp.news.forms import CommentForm
from webapp.news.models import Comments, News
from webapp.weather import weather_by_city
from webapp.utils import get_redirect_target

blueprint = Blueprint("news", __name__)


@blueprint.route('/')
def index():
    title = "Новости Python"
    weather = weather_by_city(current_app.config["WEATHER_DEFAULT_CITY"])
    news_list = News.query.filter(News.text.isnot(None)).order_by(News.published.desc()).all()
    return render_template("news/index.html", page_title=title, weather=weather, news_list=news_list)


@blueprint.route("/news/<int:news_id>")
def single_news(news_id):
    my_news = News.query.filter(News.id == news_id).first()

    if not my_news:
        abort(404)
    comment_form = CommentForm(news_id=my_news.id)
    return render_template("news/single_news.html", page_title=my_news.title, news=my_news, comment_form=comment_form)


@blueprint.route("/news/comment", methods=["POST"])
@login_required
def add_comment():
    form = CommentForm()
    if form.validate_on_submit():
        comment = Comments(text=form.comment_text.data, news_id=form.news_id.data, user_id=current_user.id)
        db.session.add(comment)
        db.session.commit()
        flash("Комментарий успешно добавлен.")
    else:
        for field, errors in form.errors.items():
            for error in errors:
                flash("Ошибка в поле {}: - {}".format(
                    getattr(form, field).label.text,
                    error
                ))
    return redirect(get_redirect_target())

webapp/templates/news/index.html
{% extends "base.html" %}

{% block content %}
    <div class="row">
        <div class="col-8">
            {% include('messages.html') %}
            <h2>Новости</h2>
            {% for news in news_list %}
            <h3><a href="{{ url_for('news.single_news', news_id=news.id) }}">{{ news.title }}</a></h3>
            <p>{{ news.published.strftime("%Y-%m-%d") }} | Комментарии: {{ news.comments_count() }}</p>
            <hr />
            {% endfor %}
        </div>
        <div class="col-4">
            <h2>Прогноз погоды</h2>
            {% if weather %}
                Температура воздуха: {{ weather.temp_C }}, ощущается как {{ weather.FeelsLikeC }}
            {% else %}
                Сервис погоды недоступен.
            {% endif %}
        </div>
    </div>
{% endblock %}

webapp/templates/news/single_news.html
{% extends "base.html" %}

{% block content %}
    <div class="row">
        <div class="col-8 news-content">
            {% include('messages.html') %}
            {{ news.text|safe }}
            {% if news.comments %}
                <h3>Комментарии:</h3>
                {% for comment in news.comments %}
                <div class="card">
                    <div class="card-body">
                        <p class="card-text">{{ comment.text }}</p>
                        <p class="card-text">
                            <small>Опубликованно: {{ comment.created.strftime('%d.%m.%Y') }} |
                                Автор: {{ comment.user.username }}</small>
                        </p>
                    </div>
                </div>
                {% endfor %}
            {% endif %}
            {% if current_user.is_authenticated %}
                <form action="{{ url_for('news.add_comment') }}" method='POST'>
                    {{ comment_form.hidden_tag() }}
                    <div class="form-group">
                        {{ comment_form.comment_text.label }}
                        {{ comment_form.comment_text() }}
                    </div>
                    {{ comment_form.submit() }}
                </form>
            {% else %}
                <p>
                    <a href='{{ url_for("user.login", next=request.full_path) }}'>Пожалуйста авторизуйтесь!</a> чтобы добавить комментарий.
                </p>
            {% endif %}
        </div>
        <div class="col-4">
            <h2>Другие новости</h2>
        </div>
    </div>
{% endblock %}