webapp/user/models.py
from flask_login import UserMixin
from werkzeug.security import generate_password_hash, check_password_hash

from webapp.db import db


class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(50), index=True, unique=True)
    password = db.Column(db.String(128))
    role = db.Column(db.String(10), index=True)
    email = db.Column(db.String(50))

    def set_password(self, password):
        self.password = generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self.password, password)

    @property
    def is_admin(self):
        return self.role == "admin"

    def __repr__(self):
        return "<User name={}, id={}>".format(self.username, self.id)

webapp/user/forms.py
from flask_wtf import FlaskForm
from wtforms import BooleanField, StringField, PasswordField, SubmitField
from wtforms.validators import DataRequired, Email, EqualTo, ValidationError

from webapp.user.models import User

class LoginForm(FlaskForm):
    username = StringField("Имя пользователя", validators=[DataRequired()], render_kw={"class": "form-control"})
    password = PasswordField("Ввдите пароль", validators=[DataRequired()], render_kw={"class": "form-control"})
    remember_me = BooleanField("Запомнить меня", default=True, render_kw={"class": "form-check-input"})
    submit = SubmitField("Отправить!", render_kw={"class": "btn btn-primary"})


class RegistrationForm(FlaskForm):
    username = StringField("Имя пользователя", validators=[DataRequired()], render_kw={"class": "form-control"})
    email = StringField("Электронаая почта", validators=[DataRequired(), Email()], render_kw={"class": "form-control"})
    password = PasswordField("Ввдите пароль", validators=[DataRequired()], render_kw={"class": "form-control"})
    password2 = PasswordField("Повторите пароль", validators=[DataRequired(), EqualTo("password")], render_kw={"class": "form-control"})
    submit = SubmitField("Отправить!", render_kw={"class": "btn btn-primary"})

    def validate_username(self, username):
        user_count = User.query.filter_by(username=username.data).count()
        if user_count > 0:
            raise ValidationError("Пользователь с таким именем уже существует!")

    def validate_email(self, email):
        user_count = User.query.filter_by(email=email.data).count()
        if user_count > 0:
            raise ValidationError("Пользователь с таким почтовым адресом уже существует!")

webapp/user/views.py
from flask import Blueprint, flash, render_template, redirect, url_for
from flask_login import current_user, login_user, logout_user

from webapp import db
from webapp.user.forms import LoginForm, RegistrationForm
from webapp.user.models import User
from webapp.utils import get_redirect_target

blueprint = Blueprint("user", __name__, url_prefix="/users")


@blueprint.route("/login")
def login():
    if current_user.is_authenticated:
        return redirect(get_redirect_target())
    title = "Авторизация"
    login_form = LoginForm()
    return render_template("user/login.html", page_title=title, form=login_form)


@blueprint.route("/process-login", methods=["GET", "POST"])
def process_login():
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter(User.username == form.username.data).first()
        if user and user.check_password(form.password.data):
            login_user(user, remember=form.remember_me.data)
            flash("Вы успешно вошли на сайт.")
            return redirect(get_redirect_target())
    flash("Неправильное имя или пароль!")
    return redirect(url_for("user.login"))


@blueprint.route("/logout")
def logout():
    logout_user()
    flash("Вы успешно разлогинились!")
    return redirect(url_for("news.index"))


@blueprint.route("/register")
def register():
    if current_user.is_authenticated:
        return redirect(url_for("news.index"))
    title = "Регистрация"
    form = RegistrationForm()
    return render_template("user/registration.html", page_title=title, form=form)


@blueprint.route("/process-reg", methods=["POST"])
def process_reg():
    form = RegistrationForm()
    if form.validate_on_submit():
        news_user = User(username=form.username.data, email=form.email.data, role="user")
        news_user.set_password(form.password.data)
        db.session.add(news_user)
        db.session.commit()
        flash("Вы успешно зарегистрировались!")
        return redirect(url_for(("user.login")))
    else:
        for field, errors in form.errors.items():
            for error in errors:
                flash("Ошибка в поле {}: - {}".format(
                    getattr(form, field).label.text,
                    error
            ))
    return redirect(url_for("user.register"))

webapp/templates/user/login.html
{% extends "base.html" %}

{% block content %}
    <div class="row">
        <div class="col-4">
            {% include('messages.html') %}
            <form action="{{ url_for('user.process_login') }}" method="POST">
                {{ form.hidden_tag() }}
                <div class="mb-3">
                    {{ form.username.label }}
                    {{ form.username() }}
                </div>
                <div class="mb-3">
                    {{ form.password.label }}
                    {{ form.password() }}
                </div>
                <div class="form-group form-check">
                    {{ form.remember_me() }}
                    {{ form.remember_me.label(class_="form-check-label") }}
                </div>
                {{ form.submit() }}
            </form>
        </div>
        <div class="col-8">

        </div>
    </div>
{% endblock %}

webapp/templates/user/registration.html
{% extends "base.html" %}

{% block content %}
    {% include('messages.html') %}
    <div class="row">
        <div class="col-4">

            <form action="{{ url_for('user.process_reg') }}" method="POST">
                {{ form.hidden_tag() }}
                <div class="mb-3">
                    {{ form.username.label }}
                    {{ form.username() }}
                </div>
                <div class="mb-3">
                    {{ form.email.label }}
                    {{ form.email() }}
                </div>
                <div class="mb-3">
                    {{ form.password.label }}
                    {{ form.password() }}
                </div>
                <div class="mb-3">
                    {{ form.password2.label }}
                    {{ form.password2() }}
                </div>
                {{ form.submit() }}
            </form>
        </div>
        <div class="col-8">

        </div>
    </div>
{% endblock %}