webapp/admin/views.py
from flask import Blueprint, render_template
from webapp.user.decorators import admin_required

blueprint = Blueprint("admin", __name__, url_prefix="/admin")


@blueprint.route("/")
@admin_required
def admin_index():
    title = "Панель управления"
    return render_template("admin/index.html", page_title=title)

webapp/user/views.py
from flask import Blueprint, flash, render_template, redirect, url_for
from flask_login import current_user, login_user, logout_user

from webapp import db
from webapp.user.forms import LoginForm, RegistrationForm
from webapp.user.models import User
from webapp.utils import get_redirect_target

blueprint = Blueprint("user", __name__, url_prefix="/users")


@blueprint.route("/login")
def login():
    if current_user.is_authenticated:
        return redirect(get_redirect_target())
    title = "Авторизация"
    login_form = LoginForm()
    return render_template("user/login.html", page_title=title, form=login_form)


@blueprint.route("/process-login", methods=["GET", "POST"])
def process_login():
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter(User.username == form.username.data).first()
        if user and user.check_password(form.password.data):
            login_user(user, remember=form.remember_me.data)
            flash("Вы успешно вошли на сайт.")
            return redirect(get_redirect_target())
    flash("Неправильное имя или пароль!")
    return redirect(url_for("user.login"))


@blueprint.route("/logout")
def logout():
    logout_user()
    flash("Вы успешно разлогинились!")
    return redirect(url_for("news.index"))


@blueprint.route("/register")
def register():
    if current_user.is_authenticated:
        return redirect(url_for("news.index"))
    title = "Регистрация"
    form = RegistrationForm()
    return render_template("user/registration.html", page_title=title, form=form)


@blueprint.route("/process-reg", methods=["POST"])
def process_reg():
    form = RegistrationForm()
    if form.validate_on_submit():
        news_user = User(username=form.username.data, email=form.email.data, role="user")
        news_user.set_password(form.password.data)
        db.session.add(news_user)
        db.session.commit()
        flash("Вы успешно зарегистрировались!")
        return redirect(url_for(("user.login")))
    else:
        for field, errors in form.errors.items():
            for error in errors:
                flash("Ошибка в поле {}: - {}".format(
                    getattr(form, field).label.text,
                    error
            ))
    return redirect(url_for("user.register"))

webapp/templates/base.html
<!doctype html>
<html lang="ru">
  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.5.1/styles/atom-one-dark.min.css" rel="stylesheet">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.5.1/highlight.min.js"></script>
    <script>hljs.initHighlightingOnLoad();</script>
    <link  href="{{ url_for('static', filename='style.css') }}" rel='stylesheet'>
    <title>{{ page_title }}</title>
  </head>
  <body>
    {% include "menu.html" %}
    <div class="container">
        <h1>{{ page_title }}</h1>
        {% block content %}{% endblock %}
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
  </body>
</html>

webapp/templates/menu.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">Новости Python</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                  <a class="nav-link active" aria-current="page" href="/">Главная страница</a>
                </li>
            </ul>
            <form class="d-flex">
                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success" type="submit">Искать</button>
            </form>
            <ul class="navbar-nav">
                {% if current_user.is_authenticated %}
                    <li class="nav-item">
                        <span class="nav-link">Привет, {{ current_user.username }}</span>
                    </li>
                    {% if current_user.is_admin %}
                        <li class="nav-item">
                            <a class="nav-link" href='{{ url_for("admin.admin_index") }}'>Админка</a>
                        </li>
                    {% endif %}
                    <li class="nav-item">
                        <a class="nav-link" href='{{ url_for("user.logout") }}'>Выйти</a>
                    </li>
                {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href='{{ url_for("user.register") }}'>Регистрация</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href='{{ url_for("user.login") }}'>Войти</a>
                        </li>
                {% endif %}
          </ul>
        </div>
    </div>
</nav>

webapp/templates/messages.html
{% with messages = get_flashed_messages() %}
    {% if messages %}
    <div class=" alert alert-warning" role="alert">
        {% for message in messages %}
            {{ message }}<br>
        {% endfor %}
    </div>
    {% endif %}
{% endwith %}